<?php
$addr=$this->getParentBlock();
?>
<?php 
    $checkout = Mage::getSingleton('checkout/session')->getQuote();
    $billing = $checkout->getBillingAddress();
    $billing->getCity();
 ?>
                    <div class="">
                        <label for="billing:city" class="required"><em>*</em><?php echo $addr->__('City') ?></label>
                        <div class="input-box">
                            <select id="billing:city" name="billing[city]" title="<?php echo $addr->__('City') ?>" class="validate-select">
                                <option value=""><?php echo $this->__('Seleccione su ciudad') ?></option>
                            </select>
                        </div>
                    </div>
                    <script language="javascript">
					jQuery(document).ready(function(){
						jQuery('#billing\\:city').attr('defaultValue',  "<?php echo $billing->getCity(); ?>");
						jQuery('#billing\\:city').cityUpdater('#billing\\:region_id', <?php echo $this->helper('cities')->getCityJson(); ?>, {disableAction:"disable"});
					});
					</script>