<?php
$addr=$this->getParentBlock();
?>
<?php 
    $checkout = Mage::getSingleton('checkout/session')->getQuote();
    $shipping = $checkout->getShippingAddress();
    $shippingcity = $shipping->getCity();
 ?>
                    <div class="">
                        <label for="shipping:city" class="required"><em>*</em><?php echo $addr->__('City') ?></label>
                        <div class="input-box">
                            <select id="shipping:city" name="shipping[city]" title="<?php echo $addr->__('City') ?>" class="validate-select">
                                <option value=""><?php echo $this->__('Seleccione su ciudad') ?></option>
                            </select>
                        </div>
                    </div>
                    <script language="javascript">
					jQuery(document).ready(function(){
						jQuery('#shipping\\:city').attr('defaultValue',  "<?php echo $shippingcity; ?>");
						jQuery('#shipping\\:city').cityUpdater('#shipping\\:region_id', <?php echo $this->helper('cities')->getCityJson(); ?>, {disableAction:"disable"});
					});
					</script>