<?php if ($this->getInstructions()): ?>
	<!--
	<ul class="form-list checkout-agreements" id="payment_form_<?php //echo $this->getMethodCode() ?>" style="display:none;">
        <li>
        	<?php //echo nl2br($this->getInstructions()) ?>
        </li>
    </ul>
	-->
<?php endif; ?>

    <div class="<?php echo $this->getMethodCode() ?>-instructions-content agreement-content" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <div id="payment_form_<?php echo $_code ?>">
			<p>Para su pago de contra entrega tenga en cuenta:</p>
			<ul class="form-list">
				<li>Pago solo en efectivo.</li>
				<li>Cubrimiento del 80% del país.</li>
				<li>Tenga el monto exacto de su compra a la mano.</li>
				<li>Si usted no está presente puede dejar el monto a otro familiar o conocido.</li>
				<li>Este pendiente del arribo de su pedido.</li>
				<li>Recuerde que los mensajeros no tienen cambio.</li>
			</ul>
			<br />
			<p>Si quiere conocer cuáles son los puntos en los cuales se puede realizar entregas busque <a href="/calculo-de-envios" target="_blank">aquí</a>.</p>
		</div>
    </div>
        

