
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $m = Mage::getModel('catalog/resource_eav_attribute')->loadByCode('catalog_product','productlayout');
?>
<?php $pagelayout = $this->htmlEscape($_product->getPageLayout()); ?>
<?php if($pagelayout == '' || $pagelayout == 'one_column'){ ?>

<!--Start theme layout-->
<?php
if(Mage::helper("ExtraConfig")->is_mobile() == true) {
    $layout = 'vertical';
} else {
    $layout = Mage::helper("ExtraConfig")->themeOptions('productlayout');
    
    if($m->getId() != null) {
	$lyt = $_product->getAttributeText('productlayout');
	if($lyt != null){ $layout = $lyt; }
    }
}
if ($layout == 'default')
{ ?>


<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 1) {
   
    
    $gallery .= '<div id="slider" class="flexslider">';
    $gallery .= '<h2>' . $this->__('More Views') . '</h2>';
    $gallery .= '<ul class="slides">';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(78,98) . '" alt="' . $this->htmlEscape($_image->getLabel()) . '" width="" height="" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
} else {
				
$gallery .= '<div class="without-image"></div>';

}
?>

<?php
}
elseif ($layout == 'horizontal')
{ ?>


<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 1) {
    
    $gallery .= '<div id="slider" class="flexslider">';
    $gallery .= '<h2>' . $this->__('More Views') . '</h2>';
    $gallery .= '<ul class="slides">';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(78,98) . '" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
} else {
				
 $gallery .= '<div class="without-image"></div>';

}
?>

<?php
}
elseif ($layout == 'vertical')
{ ?>


<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 1) {
    
    $gallery .= '<div id="slider" class="flexslider">';
    $gallery .= '<h2>' . $this->__('More Views') . '</h2>';
    $gallery .= '<ul class="slides">';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(78,98) . '" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
} else {
				
$gallery .= '<div class="without-image"></div>';

}
?>


<?php
}
elseif ($layout == 'custom1')
{ ?>


<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 1) {
    
    $gallery .= '<div id="slider" class="flexslider">';
    $gallery .= '<h2>' . $this->__('More Views') . '</h2>';
    $gallery .= '<ul class="slides">';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(78,98) . '" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
} else {
				
$gallery .= '<div class="without-image"></div>';

}
?>

<?php
}
elseif ($layout == 'custom2')
{ ?>

<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 1) {
    
    $gallery .= '<div id="carousel2" class="flexslider"><ul class="slides">';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(63,63) . '" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
} else {
				
$gallery .= '<div class="without-image"></div>';

}
?>

<?php } ?>



<?php
if ($layout == 'default')
{ ?>

   
       
	
        <div class="default-views detail-carousel cloudzoom">
				<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
				<p class="product-image product-image-zoom">
				    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
				    <?php
					$_img = '<img id="image" itemprop="image" src="'.$this->getCloudImage($_product).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" width="352" height="360" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				    </a>
				</p>
				<?php else: ?>
				<p class="product-image">
				    <?php
					$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(352,360).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" width="352" height="360"/>';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				</p>
				<?php endif; ?>
        
			     <?php if(isset($gallery)): ?>
				 <?php echo $gallery; ?>
			    <?php endif; ?>
        
        
        
        </div>
    
 <script>
  j$('#slider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 90,
    itemMargin: 10
  });
   
 
   
  
</script>
 <?php
}
elseif ($layout == 'horizontal')
{ ?>   
    
    
       
	
        <div class="horizontal-views detail-carousel cloudzoom">
         
				<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
				<p class="product-image product-image-zoom">
				    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
				    <?php
					$_img = '<img id="image" itemprop="image" src="'.$this->getCloudImage($_product).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" width="352" height="360" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				    </a>
				</p>
				<?php else: ?>
				<p class="product-image">
				    <?php
					$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(478,360).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				</p>
				<?php endif; ?>
			    <?php if(isset($gallery)): ?>
				 <?php echo $gallery; ?>
			    <?php endif; ?>
        
        
        
        </div>
    
 <script>
  j$('#slider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 90,
    itemMargin: 10
  });
   
 
   
  
</script>
    
    <?php
}
elseif ($layout == 'vertical')
{ ?>
    
    
       
	
        <div class="vertical-views detail-carousel cloudzoom">
         
				<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
				<p class="product-image product-image-zoom">
				    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
				    <?php
					$_img = '<img id="image" itemprop="image" src="'.$this->getCloudImage($_product).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" width="352" height="360" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				    </a>
				</p>
				<?php else: ?>
				<p class="product-image">
				    <?php
					$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(278,360).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				</p>
				<?php endif; ?>
				
			<?php if(isset($gallery)): ?>
				<?php echo $gallery; ?>
			<?php endif; ?>
        
        
        
        </div>
    
 <script>
  j$('#slider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 90,
    itemMargin: 10
  });
   
  
   
  
</script>
    
    
    <?php
}
elseif ($layout == 'custom1')
{ ?>   
    
    
       
	
        <div class="custom1-views detail-carousel cloudzoom">
         
				<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
				<p class="product-image product-image-zoom">
				    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
				    <?php
					$_img = '<img id="image" itemprop="image" src="'.$this->getCloudImage($_product).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" width="352" height="360" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				    </a>
				</p>
				<?php else: ?>
				<p class="product-image">
				    <?php
					$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(879,500).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				</p>
				<?php endif; ?>
				
			    <?php if(isset($gallery)): ?>
				<?php echo $gallery; ?>
			    <?php endif; ?>
        
        
        
        </div>
    
 <script>
 j$('#slider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 90,
    itemMargin: 10
  });
   
  
   
  
</script>
    
    
    <?php
}
elseif ($layout == 'custom2')
{ ?>


       
	
        <div class="custom2-views detail-carousel cloudzoom">
				
				
				
				<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
				<p class="product-image product-image-zoom">
				    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
				    <?php
					$_img = '<img id="image" itemprop="image" src="'.$this->getCloudImage($_product).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" width="352" height="360" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				    </a>
				</p>
				<?php else: ?>
				<p class="product-image">
				    <?php
					$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(502,360).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				</p>
				<?php endif; ?>
				
			    <?php if(isset($gallery)): ?>
				<?php echo $gallery; ?>
			    <?php endif; ?>
        
        
        </div>
    
 <script>
  j$('#carousel2').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    direction: "vertical",
    slideshow: false,
    //itemWidth: 75,
    itemMargin: 10
  });
   
 
  
</script>

<?php
}
?>

<!--End theme layout-->

<?php } else { ?>

<?php
$mainImagePath = '';
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 1) {
   
    
    $gallery .= '<div id="slider" class="flexslider">';
    $gallery .= '<h2>' . $this->__('More Views') . '</h2>';
    $gallery .= '<ul class="slides">';
    foreach ($galleryImages as $_image) {
        if ($_image->getFile() == $_product->getData('small_image')) {
            $mainImagePath = $this->getGalleryUrl($_image);
        }
        $gallery .= '<li>'
                 .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                 .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                 .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(78,98) . '" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                 .  '</a></li>';
    }
    $gallery .= '</ul></div>';
} else {
				
$gallery .= '<div class="without-image"></div>';

}
?>
 
 
 <div class="default-views detail-carousel cloudzoom">
				<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
				<p class="product-image product-image-zoom">
				    <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
				    <?php
					$_img = '<img id="image" itemprop="image" src="'.$this->getCloudImage($_product).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" width="352" height="360" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				    </a>
				</p>
				<?php else: ?>
				<p class="product-image">
				    <?php
					$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(352,360).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" width="352" height="360"/>';
					echo $_helper->productAttribute($_product, $_img, 'image');
				    ?>
				</p>
				<?php endif; ?>
        
			     <?php if(isset($gallery)): ?>
				 <?php echo $gallery; ?>
			    <?php endif; ?>
        
        
        
        </div>
    
 <script>
  j$('#slider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 90,
    itemMargin: 10
  });
   
 
   
  
</script>
 
<?php } ?>