<?php $_manufacturersCollection = $this->getManufacturersCollection(); ?>
<?php $_columnCount = 8; ?>
<div>
    <div class="page-title">
        <h1><?php echo $this->__('Manufacturers') ?></h1>
    </div>
    <?php $i=0; foreach ($_manufacturersCollection as $_manufacturer): ?>
    <?php if ($i++%$_columnCount==0): ?>
    <ul class="products-grid first odd">
    <?php endif ?>
        <?php 
            $url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "manufacturer/" .$_manufacturer->getManufacturerLogo(); 
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL,$url);
            // don't download content
            curl_setopt($ch, CURLOPT_NOBODY, 1);
            curl_setopt($ch, CURLOPT_FAILONERROR, 1);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            
            if(curl_exec($ch)!==FALSE){
        ?>
        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
            <a href="<?php echo $this->getUrl($_manufacturer->getIdentifier()) ?>" title="<?php echo $_manufacturer->getManufacturer() ?>"><img alt="<?php echo $_manufacturer->getManufacturerLogo() ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'manufacturer' . '/' . $_manufacturer->getManufacturerLogo() ?>" width="150" height="60"></a>            
            <!--<h2><a href="<?php echo $this->getUrl('marca' . '/' . $_manufacturer->getIdentifier()) ?>" title="<?php echo $_manufacturer->getManufacturer() ?>"><?php echo $_manufacturer->getManufacturer(); ?></a></h2>-->
        </li>
        <?php } ?>
        <?php if ($i%$_columnCount==0 || $i==count($_manufacturersCollection)): ?>
    </ul>
    <?php endif ?>
    <?php endforeach; ?>
</div>
