<?php $_manufacturer = $this->getManufacturer(); ?>
<?php $processor = Mage::helper('zeon_manufacturer')->getBlockTemplateProcessor(); ?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $newsaleicon = Mage::helper("ExtraConfig")->themeOptions('newsaleicon');
    $ajaxcart = Mage::helper("ExtraConfig")->themeOptions('ajaxcart');
    $displaycategorysidebar = Mage::helper("ExtraConfig")->themeOptions('displaycategorysidebar');
    $homeproduct = Mage::helper("ExtraConfig")->themeOptions('homeproduct');
    $_helper = $this->helper('catalog/output');
?>
<div class="page-head">
    <h3><?php echo Mage::getModel('zeon_manufacturer/manufacturer')->getManufacturerName($_manufacturer->getManufacturer(), Mage::app()->getStore()->getId()) ?></h3>
</div>
<div class="category">
   <div class="clearfix" style="margin-bottom: 1px";>
		<p class="category-image">
			<?php if($_manufacturer->getManufacturerBanner()):?>
	        <a href="#"><img alt="<?php echo $_manufacturer->getManufacturerBanner() ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'manufacturer' . '/' . $_manufacturer->getManufacturerBanner() ?>" height="300" width="700"></a> 
			<?php endif; ?>
		</p>
		<div class="category-description std category-block">
	
			<div class="right" >
	            <a href="<?php echo $this->getCurrentUrl() ?>"><img alt="<?php echo $_manufacturer->getManufacturerLogo() ?>" title="<?php echo $_manufacturer->getManufacturerLogo() ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'manufacturer' . '/' . $_manufacturer->getManufacturerLogo() ?>" width="100" height="40"></a>
	        </div>
            <?php echo $processor->filter($_manufacturer->getDescription()); ?>
		</div>
    </div>
<?php  $_products = $this->getProductCollection(); 
 $_collectionSize = $_products->getSize();?>   
<?php if (empty($_collectionSize)): ?>
	<div id="messages_product_view">
    <ul class="messages">
        <li class="note-msg">
            <ul>
                <li>
                    <span><?php echo $this->__('There are no products matching the selection.') ?></span>
                </li>
            </ul>
        </li>
     </ul>
     </div>
<?php else: ?>
	 <div class="category-products">
    	<?php echo $this->getToolbarHtml() ?>
	    <?php if (($_products = $this->getProductCollection()) && $_collectionSize = $_products->getSize()): ?>
	    
	    <?php if($this->getMode()!='grid'): ?>
	   
	    <?php $_iterator = 0; ?>
        <ol class="products-list" id="products-list">
	        <?php foreach ($_products->getItems() as $_product): ?>
	        	<li class="item<?php if( ++$_iterator == sizeof($_products->getItems()) ): ?> last<?php endif; ?>">
	               <div class="list-icon">
		<?php if($newsaleicon == '1') { ?> 
			<?php $gdate = date('Y-m-d');  //echo 'frpm:-'.$_product->special_from_date.'----';echo "to:-".$_product->special_to_date.'--';
			$g= 0;
			if($_product->special_from_date != null && $_product->special_to_date == "")
			{
			    if( $gdate >= $_product->special_from_date)
			    {
				    $g = 1; 
			    }
			}
			if($_product->special_from_date != "" && $_product->special_to_date != "")
			{
			    if($gdate >= $_product->special_from_date && $gdate <= $_product->special_to_date)
			    {
			    $g = 1; 
			    }
			}
			    
			    if($g == 1){ ?>
			   <div class="sale"><label><?php echo $this->__('SALE') ?></label></div>
			    <?php } ?>
			
			
		      <?php $hdate = date('Y-m-d');
			$h= 0;
			if($_product->news_from_date != null && $_product->news_to_date == "")
			{
			    if( $hdate >= $_product->news_from_date)
			    {
				    $h = 1; 
			    }
			}
			if($_product->news_from_date != "" && $_product->news_to_date != "")
			{
			    if($hdate >= $_product->news_from_date && $hdate <= $_product->news_to_date)
			    {
			    $h = 1; 
			    }
			}
			    if($h == 1){ ?>
			   <div class="new"><label><?php echo $this->__('NEW') ?></label></div>
			    <?php } 
			?>  
		<?php } ?>              
		<?php // Product Image ?>
		
		<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">   
		    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(true)->keepAspectRatio(true)->resize(252,248); ?>" width="252" height="248" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
		</a>
		
		    <?php if($ajaxcart == '2') { ?>
			<a tabindex="1" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' title="<?php // echo $this->__('Quick View') ?>" class='fancybox quick-view' id='fancybox<?php echo $_product->getId()?>'><?php echo $this->__('Quick View') ?></a>
		    <?php } ?>		
		
	    </div>
	    <?php // Product description ?>
	    <?php if ($displaycategorysidebar == 'full') { ?>
	    <div class="product-shop product-shopfull">
            <?php } else { ?>
	    <div class="product-shop product-shop">
	    <?php } ?>
                <div class="f-fix">
		    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
		    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
		    
		    <?php // if($_product->getRatingSummary()): ?>
			<?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
		    <?php // endif; ?>
		    
		    <?php echo $this->getPriceHtml($_product, true) ?>
		    <!--<div class="productlist-area">
			
		    </div>-->
		    <div class="desc std">
			<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
		    </div>
		    <div class="list-action">
			
			<?php if($_product->isSaleable()): ?>
			    <?php if($ajaxcart == '1' || $ajaxcart == '2') { ?>
				<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
				<p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajx-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><i class="icon-plus"></i><span><?php echo $this->__('Add To Cart') ?></span></span></button></p>
				<div id='ajax_loader<?php echo $_product->getId()?>' class="ajaxcartpro_progress" style="display: none;">
				    <img src="<?php echo $this->getSkinUrl('ajaxcart/images/al.gif'); ?>" width="47" height="47">
				    <p><?php echo $this->__('Please wait...') ?></p>
							<div><?php echo $this->__('We are updating Shopping Bag.') ?></div>
				</div>
				<?php } else { ?>
					<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="icon-plus"></i><span><?php echo $this->__('Add To Cart') ?></span></span></button>
				<?php }  ?>
			    <?php } else { ?>
				<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="icon-plus"></i><span><?php echo $this->__('Add To Cart') ?></span></span></button>
			    <?php } ?>
			<?php else: ?>
			    <button type="button" class="availability out-of-stock"><span><i class="icon-plus"></i><span><?php echo $this->__('Out of stock') ?></span></span></button>
			<?php endif; ?>			
			
			
			
			<ul class="add-to-links">
			    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
				<li class="first"><a href="<?php echo $_compareUrl ?>" title="<?php // echo $this->__('Add to Compare') ?>" class="link-compare"><div class="tooltip"><?php echo $this->__('Add to Compare') ?><div class="errow"></div></div></a></li>
			    <?php endif; ?>
			    <?php if ($this->helper('wishlist')->isAllow()) : ?>
				<li class="last"><span class="separator">|</span><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php // echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><div class="tooltip"><?php echo $this->__('Add to Wishlist') ?><div class="errow"></div></div></a></li>
			    <?php endif; ?>			    
			    
			</ul>
		    	
			
			
		    </div>
                </div>
            </div>
	            </li>
	        <?php endforeach; ?>
	    </ol>
        <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
        <?php else: ?>

        <?php $_columnCount = 3; ?>
        <?php $i = 0; foreach ($_products->getItems() as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid first odd">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <div class="product-content">
		    <div class="content_img_icon">
		    <?php if($newsaleicon == '1') { ?> 
			<?php $edate = date('Y-m-d');  //echo 'frpm:-'.$_product->special_from_date.'----';echo "to:-".$_product->special_to_date.'--';
			$e= 0;
			if($_product->special_from_date != null && $_product->special_to_date == "")
			{
			    if( $edate >= $_product->special_from_date)
			    {
				    $e = 1; 
			    }
			}
			if($_product->special_from_date != "" && $_product->special_to_date != "")
			{
			    if($edate >= $_product->special_from_date && $edate <= $_product->special_to_date)
			    {
			    $e = 1; 
			    }
			}
			    
			    if($e == 1){ ?>
			   <div class="sale"><label><?php echo $this->__('SALE') ?></label></div>
			    <?php } ?>
			
			
		      <?php $fdate = date('Y-m-d');
			$f= 0;
			if($_product->news_from_date != null && $_product->news_to_date == "")
			{
			    if( $fdate >= $_product->news_from_date)
			    {
				    $f = 1; 
			    }
			}
			if($_product->news_from_date != "" && $_product->news_to_date != "")
			{
			    if($fdate >= $_product->news_from_date && $fdate <= $_product->news_to_date)
			    {
			    $f = 1; 
			    }
			}
			    if($f == 1){ ?>
			   <div class="new"><label><?php echo $this->__('NEW') ?></label></div>
			    <?php } 
			?>  
		    <?php } ?>                                   
		     
		    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
			<?php if($homeproduct == '1'){ ?>	
			<img class="small-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(263,320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"width="263" height="320" />
			<img class="thumbnail" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(263,320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" width="263" height="320" />
			<?php } else { ?>
			<img class="small-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" width="320" height="320" />
			<img class="thumbnail" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" width="320" height="320" />
			<?php } ?>
		    </a>
		    
		    <?php if($ajaxcart == '2') { ?>
			<a tabindex="1" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' title="<?php // echo $this->__('Quick View') ?>" class='fancybox quick-view' id='fancybox<?php echo $_product->getId()?>'><?php echo $this->__('Quick View') ?></a>
		    <?php } ?>
		    
		    <div class="productgrid-area">
		       
			<?php
				$productName = $this->htmlEscape($_product->getName());
				if($homeproduct == '0'){
				    if(strlen($productName) > 20) {
					    $productName = mb_strimwidth($productName,0,20,"...",'utf-8');
				    } 
				} else {
				    if(strlen($productName) > 33) {
					    $productName = mb_strimwidth($productName,0,33,"...",'utf-8');
				    }
				}
			?>
		    
				 
			<div class="actions">
	    
			    <?php if($_product->isSaleable()): ?>
				<?php if($ajaxcart == '1' || $ajaxcart == '2') { ?>
				    <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
				    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajx-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><i class="icon-plus"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button> 
				    
				    <?php } else { ?>
					    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="icon-plus"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button>
					    
				    <?php }  ?>
				<?php } else { ?>
				    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="icon-plus"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button>
				<?php } ?>
			    <?php else: ?>
				<button type="button" class="availability out-of-stock"><span><i class="icon-plus"></i><span><?php echo $this->__('Out of stock') ?></span></span></button>
			    <?php endif; ?>
			    
			    
			   
			    <ul class="add-to-links">
				<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
				    <li><a href="<?php echo $_compareUrl ?>" title="<?php // echo $this->__('Add to Compare') ?>" class="link-compare"><div class="tooltip"><?php echo $this->__('Add to Compare') ?><div class="errow"></div></div></a></li>
				<?php endif; ?>				
				<?php if ($this->helper('wishlist')->isAllow()) : ?>
				    <li><span class="separator">|</span><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php // echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><div class="tooltip"><?php echo $this->__('Add to Wishlist') ?><div class="errow"></div></div></a></li>
				<?php endif; ?>
			       
			    </ul>
		    
			</div>
		    </div>
		    </div>
		
		
		    <div class="actions1">
			<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $productName; ?></a></h2>
			<div class="vert">
			    <?php echo $this->getPriceHtml($_product, true) ?>
			</div>
			<?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
		    </div>
		    
		</div>
		
		<div id='ajax_loader<?php echo $_product->getId()?>' class="ajaxcartpro_progress" style="display: none;">
		    <img src="<?php echo $this->getSkinUrl('ajaxcart/images/al.gif'); ?>" width="47" height="47">
		    <p><?php echo $this->__('Please wait...') ?></p>
		    <div><?php echo $this->__('We are updating Shopping Bag.') ?></div>
		</div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==count($_products->getItems())): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
    <?php endif; ?>
    <?php endif;?>
    </div>
<?php endif; ?>    
    
    
</div>