
<div class="clear">&nbsp;</div>
    
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    
?>

<?php
$ajaxcart = Mage::helper("ExtraConfig")->themeOptions('ajaxcart');
$homeproduct = Mage::helper("ExtraConfig")->themeOptions('homeproduct');
$newsaleicon = Mage::helper("ExtraConfig")->themeOptions('newsaleicon');
$page = Mage::app()->getLayout()->getBlock('root')->getTemplate();
?>
    
    <?php if($homeproduct == '0') { ?>
    <div class="featured-product small-grid">
	<?php } else { ?>
	<div class="featured-product">
	<?php } ?>
	    
	<div class="new-arrow1">
	<h2 class="page-title subtitle"><?php echo $this->__('Productos Destacados') ?></h2>
	</div>
	
	
      
    <?php $_collectionSize = $_productCollection->count() ?>
	
	
	<?php if($homeproduct == '1' && $page == 'page/1column.phtml') { ?>
	    <style>.cms-home .col-main{width: 100%;}</style>
	    <?php $columnCount = 4; $this->setColumnCount($columnCount); $_columnCount = $this->getColumnCount(); ?>
	    <div class="slider1 column1">
	<?php } elseif($homeproduct == '1' && $page == 'page/2columns-left.phtml'){ ?>
	    <?php $columnCount = 3; $this->setColumnCount($columnCount); $_columnCount = $this->getColumnCount(); ?>
	    <div class="slider111 column2">
	<?php } elseif($homeproduct == '1' && $page == 'page/2columns-right.phtml'){ ?>
	    <?php $columnCount = 3; $this->setColumnCount($columnCount); $_columnCount = $this->getColumnCount(); ?>
	    <div class="slider111 column2">
	<?php } elseif($homeproduct == '1' && $page == 'page/3columns.phtml'){ ?>
	    <?php $columnCount = 3; $this->setColumnCount($columnCount); $_columnCount = $this->getColumnCount(); ?>
	    <div class="slider11 column3 small">
	<?php } elseif($homeproduct == '0' && $page == 'page/1column.phtml'){ ?>
	    <style>.cms-home .col-main{width: 100%;}</style>
	    <?php $columnCount = 6; $this->setColumnCount($columnCount); $_columnCount = $this->getColumnCount(); ?>
	    <div class="slider1 column11 small">
	<?php } elseif($homeproduct == '0' && $page == 'page/2columns-left.phtml'){ ?>
	    <?php $columnCount = 4; $this->setColumnCount($columnCount); $_columnCount = $this->getColumnCount(); ?>
	    <div class="slider1 column12 small">
	<?php } elseif($homeproduct == '0' && $page == 'page/2columns-right.phtml'){ ?>
	    <?php $columnCount = 4; $this->setColumnCount($columnCount); $_columnCount = $this->getColumnCount(); ?>
	    <div class="slider1 column12 small">
	<?php } elseif($homeproduct == '0' && $page == 'page/3columns.phtml'){ ?>
	    <?php $columnCount = 3; $this->setColumnCount($columnCount); $_columnCount = $this->getColumnCount(); ?>
	    <div class="slider1 column13 small">
	<?php } ?>
	
	
	<?php $i=0;$j=0; foreach ($_productCollection as $_product): ?>
	<?php if ($i++%$_columnCount==0): ?> <ul class="products-grid"> <?php endif; ?> 	
	
		<?php if($i<5): ?>

	    <li class="item">
	    
	
		<div class="product-content">
		
		    <div class="content_img_icon">
		
		<?php if($newsaleicon == '1') { ?> 
		<?php $adate = date('Y-m-d');  //echo 'frpm:-'.$_product->special_from_date.'----';echo "to:-".$_product->special_to_date.'--';
			$a= 0;
			if($_product->special_from_date != null && $_product->special_to_date == "")
			{
			    if( $adate >= $_product->special_from_date)
			    {
				    $a = 1; 
			    }
			}
			if($_product->special_from_date != "" && $_product->special_to_date != "")
			{
			    if($adate >= $_product->special_from_date && $adate <= $_product->special_to_date)
			    {
			    $a = 1; 
			    }
			}
			    
			    if($a == 1){ ?>
			   <div class="sale"><label><?php echo $this->__('SALE') ?></label></div>
			    <?php } ?>
			
			
		      <?php $bdate = date('Y-m-d');
			$b= 0;
			if($_product->news_from_date != null && $_product->news_to_date == "")
			{
			    if( $bdate >= $_product->news_from_date)
			    {
				    $b = 1; 
			    }
			}
			if($_product->news_from_date != "" && $_product->news_to_date != "")
			{
			    if($bdate >= $_product->news_from_date && $bdate <= $_product->news_to_date)
			    {
			    $b = 1; 
			    }
			}
			    if($b == 1){ ?>
			   <div class="new"><label><?php echo $this->__('NEW') ?></label></div>
			    <?php } 
			?>  
		<?php } ?>
		
		    
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
			    <?php if($homeproduct == '1' && $page != 'page/3columns.phtml'){ ?>	
			    <img class="small-image" width="282" height="320" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(263,320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			    <img class="thumbnail" width="282" height="320" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(263,320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			    <?php } else { ?>
			    <img class="small-image" width="320" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			    <img class="thumbnail" width="320" height="320" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(320); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			    <?php } ?>
			</a>
		     
		     
		    <?php if($ajaxcart == '2') { ?>
			<a tabindex="1" href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' title="<?php // echo $this->__('Quick View') ?>" class='fancybox quick-view' id='fancybox<?php echo $_product->getId()?>'><?php echo $this->__('Quick View') ?></a>
		    <?php } ?>
		     
		    <div class="productgrid-area">
		     
			<?php $productName = $this->htmlEscape($_product->getName());
			 if($homeproduct == '0' || $page == 'page/3columns.phtml'){
				if(strlen($productName) > 20) {
				    //$productName = mb_strimwidth($productName,0,20,"...",'utf-8');
				}
			    } else {
				if(strlen($productName) > 33) {
					//$productName = mb_strimwidth($productName,0,33,"...",'utf-8');
				}
			    }
			?>
									    
			<div class="actions">			    
			    <?php if($_product->isSaleable()): ?>
				<?php if($ajaxcart == '1' || $ajaxcart == '2') { ?>
				    <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
				    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajx-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><i class="icon-plus"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button> 
				    
				    <?php } else { ?>
					    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="icon-plus"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button>
					    
				    <?php }  ?>
				<?php } else { ?>
				    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="icon-plus"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button>
				<?php } ?>
			    <?php else: ?>
				<button type="button" class="availability out-of-stock"><span><i class="icon-plus"></i><span><?php echo $this->__('Out of stock') ?></span></span></button>
			    <?php endif; ?>			    
			
			    <div class="add-to-links">
				<?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
				    <a href="<?php echo $_compareUrl ?>" title="<?php // echo $this->__('Add to Compare') ?>" class="link-compare"><div class="tooltip"><?php echo $this->__('Add to Compare') ?><div class="errow"></div></div></a>
				<?php endif; ?>
				<?php if ($this->helper('wishlist')->isAllow()) : ?>
				    <span class="separator">|</span><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" title="<?php // echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><div class="tooltip"><?php echo $this->__('Add to Wishlist') ?><div class="errow"></div></div></a>
				<?php endif; ?>
			    </div>			     
			     
			</div>
		    </div>
		    </div>
		    
		    <div class="actions1">
			<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $productName; ?></a></h2>
			
			<div class="vert">
			    <?php echo $this->getPriceHtml($_product, true) ?>

			    <?php if ($_product->getResource()->getAttribute('units')->getFrontend()->getValue($_product) != "") echo "<div class='units'>". $_product->getResource()->getAttribute('units')->getFrontend()->getValue($_product) ."</div>";?>
			</div>
			<?php //echo $this->getReviewsSummaryHtml($_product, false, true) ?>
		    </div>		    
		    
		</div>
		
		<div id='ajax_loader<?php echo $_product->getId()?>' class="ajaxcartpro_progress1" style="display: none;">
		    <img src="<?php echo $this->getSkinUrl('ajaxcart/images/al.gif'); ?>" width="47" height="47">
		    <p><?php echo $this->__('Please wait...') ?></p>
		    <div><?php echo $this->__('We are updating Shopping Bag.') ?></div>
		</div>
		
            </li>
	 
	 	<?php endif ?>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
	</ul>
	<?php endif ?>
	
	
	<?php endforeach ?>
	
	
	</div>
	    
    </div>
	