<?php
$newsaleicon = Mage::helper("ExtraConfig")->themeOptions('newsaleicon');
$ajaxcart = Mage::helper("ExtraConfig")->themeOptions('ajaxcart');
$homeproduct = Mage::helper("ExtraConfig")->themeOptions('homeproduct');
$show_num_items = 100; //fixed number of items to show

?>
<?php if($this->getItems()->getSize()): ?>
 
	<div class="related-product">
	    <div class="new-arrow1">
			<h2 class="page-title subtitle"><?php echo $this->__('Related Products') ?></h2>
	    </div>

		<ul class="products-grid slider3">

			<?php $i=0;$j=0; foreach($this->getItems() as $_product): ?>
	    	<li class="slides">
	    		
	    		<a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                	<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(106,100); ?>" width="106" height="100" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
            	</a>

			    <div class="popular-content">
					<?php
					$productname = $this->htmlEscape($_product->getName());
						if(strlen($productname) > 20) {
						//$productname = mb_strimwidth($productname,0,20,"...",'utf-8');
					} ?>
			            <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $productname; ?></a></h3>
						
					<?php
					$productdesc = $_product->_data['short_description'];
						if(strlen($productdesc) > 40) {
						$productdesc = mb_strimwidth($productdesc,0,40,"...",'utf-8');
					} ?>
					<div class="desc"><?php //echo $productdesc; ?></div>
					
					<?php if ($_product->getResource()->getAttribute('units')->getFrontend()->getValue($_product) != "") echo "<div class='units'>". $_product->getResource()->getAttribute('units')->getFrontend()->getValue($_product) ."</div>";?>
					
			        <?php echo $this->getPriceHtml($_product, true) ?>
			    </div>

	    	</li>
	    	<?php endforeach ?>
		</ul>

	</div>

<?php endif; ?>