
			<h1 class="logo-wrapper">
              <span class="ir ofi-logo-main">OFI.com.co</span>
              <p>&nbsp;</p>
              <span class="tagline">- Servicio no disponible -</span>
            </h1>

            <div class="main-message bordered-box">
              <h2 class="main-copy">El servidor no puede responder su petición porque se encuentra en mantenimiento. <br/>Por favor intente mas tarde.</h2>
            </div>